void DoOutB0(byte Port ,byte Value);
void DoOutC0(byte Port ,byte Value);
void DoOutC1(byte Port ,byte Value);
void UpdateScreen(void);
void RefreshScr10(void);
void RefreshScr11(void);
void RefreshScr12(void);
void RefreshScr13(void);
void RefreshScr13a(void);
void RefreshScr13b(void);
void RefreshScr13c(void);
void RefreshScr13d(void);
void RefreshScr13e(void);
void RefreshScr51(void);
void RefreshScr52(void);
void RefreshScr53(void);
void RefreshScr54(void);
